### ISSUE TITLE
Make nvim-dap work with gdbserver

### ISSUE THREAD

**Issue by skopaas** [mfussenegger/nvim-dap#247]
### Debug adapter definition and debug configuration

I'm trying to debug a c program by running it in a separate terminal using gdbserver with this command:
```gdbserver port:1234 ./main```
How can I specify nvim-dap to run: ```target remote localhost:1234``` after starting it? Would it be possible with any other adaptations with lldb-vscode/lldb-server?

```lldb-10 --version```: lldb version 10.0.1

config files:
init.vim:
```nvim-dap
lua << EOF
local dap = require('dap')
dap.set_log_level('DEBUG')
print(vim.fn.stdpath('cache'))
dap.adapters.lldb = function(cb, config)
  local adapter = dap.adapters.c
  if config.request == 'attach' and config.program then
    local terminal = dap.defaults[config.type].external_terminal
    local full_args = {}
    vim.list_extend(full_args, terminal.args or {})
    table.insert(full_args, config.program)
    vim.list_extend(full_args, config.args or {})
    local opts = {
      args = full_args,
      detached = true
    }
    local handle
    local pid_or_err
    handle, pid_or_err = vim.loop.spawn(terminal.command, opts, function(code)
      handle:close()
      if code ~= 0 then
        print('Terminal process exited', code, 'running', terminal.command, vim.inspect(full_args))
      end
    end)
    if not handle then
      print('Could not launch process', terminal.command)
    else
      print('Launched external terminal', pid_or_err)
      while not config.pid  -- Adding a timeout or something might make sense
      do
        config.pid = tonumber(vim.fn.system({'pgrep', '-P', pid_or_err}))
      end
      print('Launched', config.program, 'within terminal with PID', config.pid)
      config.program = nil
    end
  end
  cb(adapter)
end

dap.adapters.c = {
  type = 'executable',
  command = '/usr/lib/llvm-10/bin/lldb-vscode',
  name = "lldb"
}

dap.configurations.c = {
  {
    name = "Launch",
    type = "lldb",
    request = "attach",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    args = {}
  },
}
EOF
```
launch.json:
```
{
    "configurations": [
    {
    "type": "lldb",
    "request": "attach",
    "name": "Attach to gdbserver",
    "executable": "~/Documents/main",
    "program": "~/Documents/main",
    "initCommands": [
        "target remote localhost:1234"
    ],
    "target": "127.0.0.1:1234",
    "remote": true,
    "cwd": "${workspaceFolder}",
    "miDebuggerServerAddress": "localhost:1234",
    "externalConsole": true,
    "lldbpath": "/usr/lib/llvm-10/bin/lldb-vscode", 
    "gdbpath": "/usr/bin/gdb",
    "env": { "PATH": "~/Documents" },
	  "args": []
    }
  ]
}
```

### Steps to Reproduce

Here's an example:
main.c:
```
#include <stdio.h>

int main(int argc, char **argv)
{
  const char *str = "test";
  printf("%s\n", str);
  return 0;
}
```
Normally, I would just run things like this:
1. compile with ``` gcc -g main.c -o main ```
2. write ```gdbserver port:1234 ./main ``` in another terminal
3. back in the original terminal in neovim with main.c opened, write ```:Termdebug``` 
4. once gdb or lldb was started, write ```target remote localhost:1234```  in the terminal window created by neovim
5. add a breakpoint: ```b main.c:main``` in the terminal window in neovim
6. write ```continue``` in the terminal window in neovim.
7. to terminate gdbserver if anything hangs, kill it with its pid: ```ps -aux | grep "gdbserver"```
Is there a way to emulate this with nvim-dap?

### Expected Result

The program would run with gdbserver or lldb-server in another terminal. See example above.

### Actual Result

```E5108: Error executing lua [string ":lua"]:9: attempt to index local 'terminal' (a nil value)```

**Comment by mfussenegger** [comment]
As far as I'm aware the lldb-vscode debug adapter does not support attaching to the gdbserver. You have to use vscode-cpptools instead:


Adapter installation (ansible playbook):


```
---
- name: Ensure cpptools folder exists
  file:
    path: ~/apps/cpptools
    state: directory
- name: Download cpptools
  unarchive:
    src: https://github.com/microsoft/vscode-cpptools/releases/download/1.5.1/cpptools-linux.vsix
    dest: ~/apps/cpptools/
    remote_src: true

- name: Set executable flag
  file:
    path: ~/apps/cpptools/extension/debugAdapters/{{ item }}
    mode: 0755
  loop:
    - OpenDebugAD7
    - mono.linux-x86_64

- name: Create nvim-dap.ad7Engine.json
  copy:
    src: ~/apps/cpptools/extension/cppdbg.ad7Engine.json
    dest: ~/apps/cpptools/extension/debugAdapters/bin/nvim-dap.ad7Engine.json
    remote_src: true
```


Adapter definition:

```lua
dap.adapters.cppdbg = {
  type = 'executable',
  command = HOME .. '/apps/cpptools/extension/debugAdapters/OpenDebugAD7',
}
```


Configuration:


```lua
dap.configurations.cpp = {
  {
    name = 'Attach to gdbserver',
    type = 'cppdbg',
    request = 'launch',
    MIMode = 'gdb',
    miDebuggerServerAddress = 'localhost:1234',
    miDebuggerPath = '/usr/bin/gdb',
    cwd = '${workspaceFolder}',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
  },
}
```


That you need to specify the `program` is a bit weird, given that it should debug the application you launched via the gdbserver call, but that seems to be a cpptools oddity. See also https://github.com/microsoft/vscode-cpptools/issues/6649

In action:


https://user-images.githubusercontent.com/38700/126894221-3223b22e-7ce0-4963-97e6-4dd9be3de8da.mp4
